apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedeployment
  namespace: tmb13be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: "asdasdfasfd"
        image: axas:latest
        command: ['ls']
  
      containers:
        - name: backend
          image: prashantdey/travelmemory:be
          ports:
            - containerPort: 3001
          env:
          - name: PORT
            value: "3001"
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: MONGO_URI
          volumeMounts:
            - name:  app-logs
              mountPath:  /var/log/app

        - name: logs
          image: axya:latest
          volumeMounts:
            - name:  app-logs
              mountPath:  /var/log/app