apiVersion: v1
kind: Secret 
metadata:
  name: backend-secret
  namespace: tmb13be-argocd
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGJiMTMtc2VydmljZS50bWIxM2RiLWFyZ29jZC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw==
  # mongodb://mongodbb13-service.tmb13db-argocd.svc.cluster.local:27017